#!/bin/bash

# @author: ajfernandez
# @last_edit: 2/12/18
# @Sync myDocs/ folder among my network nodes.

root="ajfernandez.me"
nodeName=(
	"jupiter"
#	"venus" -> ...config it first
	"saturn"
)

totalNodes=${#nodeName[@]}

for (( i = 0; i < totalNodes; i++ )); do
	rsync -P -rave ssh /home/ajfernandez/myDocs ajfernandez@"${nodeName[i]}".$root:~/
done
